import Layout from "@/components/layout";
import "@/styles/globals.css";
import { ThemeProvider } from "next-themes";
import type { AppProps } from "next/app";
import Head from "next/head";
import { ReactNode } from "react";
import { RecoilRoot } from "recoil";
import TimeAgo from "javascript-time-ago";
import {
  createTheme,
  ThemeProvider as MuiThemeProvider,
} from "@mui/material/styles";

import en from "javascript-time-ago/locale/en.json";
import { persistor, store } from "@/store/store";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
TimeAgo.addDefaultLocale(en);

interface ComponentWithLayout {
  getLayout?: (page: ReactNode) => ReactNode;
}

const theme = createTheme({
  palette: {
    mode: "dark",
    primary: { main: "#ff6559" },
    secondary: { main: "rgba(85, 0, 255, 0.88)" },
  },
});

export default function App({ Component, pageProps }: AppProps) {
  if ((Component as ComponentWithLayout)?.getLayout) {
    return (
      <>
        <Head>
          <title>Cipherem</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="favicon.ico" />
        </Head>
        <RecoilRoot>
          <ThemeProvider
            attribute="class"
            enableSystem={false}
            defaultTheme="dark"
          >
            <Component {...pageProps} />
          </ThemeProvider>
        </RecoilRoot>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Cipherem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <RecoilRoot>
        <Provider store={store}>
          <PersistGate persistor={persistor} loading={null}>
            <ThemeProvider
              attribute="class"
              enableSystem={false}
              defaultTheme="dark"
            >
              <MuiThemeProvider theme={theme}>
                <Layout>
                  <Component {...pageProps} />
                  <ToastContainer />
                </Layout>
              </MuiThemeProvider>
            </ThemeProvider>
          </PersistGate>
        </Provider>
      </RecoilRoot>
    </>
  );
}
